# Generated by Django 5.2.6 on 2025-10-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_default', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.TextField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
