# Generated by Django 5.2.6 on 2025-10-04 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_default', '0002_usuario_delete_usuarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario',
            new_name='nome',
        ),
    ]
