# Generated by Django 5.2.6 on 2025-10-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_default', '0003_rename_usuario_usuario_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='situacao',
            field=models.IntegerField(default=0),
        ),
    ]
